[package]
name = "quiz_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
postgres = {version = "0.19.2"}
serde = { version = "1.0", features = ["derive"] }
live-reload = "0.2"